name: Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: .npm
          key: node-12.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-12.x-
      - run: npm ci --prefer-offline --tmp .npm/tmp --cache .npm/cache
      - name: Build pages
        run: npm run build -- -o public --mode production
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: pages
          path: public

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - uses: actions/download-artifact@v2
        with:
          name: pages
          path: public
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit docs
        run: |
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git config --local user.name "$GITHUB_ACTOR"
          mv public/* .
          git add --all
          git commit -m "Pages for ${{ steps.date.outputs.date }}"
      - name: Push docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
